"""
Build triplets.json for the cross-lingual semantic granularity probe study.

Schema per the internal proposal §7:
  id, language, category, anchor, near, far, anchor_en, near_en, far_en, notes

Guidelines applied (§8):
- Minimal pairs: `near` is a synonym/word-order swap; `far` makes a single targeted change
  to the semantic feature being probed.
- English translations are the most natural rendering and DO NOT add disambiguating glosses
  (e.g., no "(paternal)" parentheticals in _en fields). Disambiguation lives in `notes`.
- Gender-neutral English nouns ("friend", "teacher", "doctor", "child", etc.) used where
  possible so flattening is genuine, not undone by English lexicalization.
- Comparable-frequency lexical items in `far` to avoid the model winning via frequency.

Generated by Claude as initial draft for Adyant's review (per the §8 quality bar:
"better 80 high-quality triplets than 100 noisy ones" — Adyant should spot-check the
items flagged in QA_NOTES.md and drop any that don't pass).
"""

import json
from pathlib import Path

# ============================================================================
# HINDI — kinship: paternal vs. maternal
# ============================================================================
hi_kin = [
    {
        "id": "hi_kin_001",
        "anchor": "मेरे चाचा कल आएंगे",
        "near":   "मेरे चाचा कल पहुंचेंगे",
        "far":    "मेरे मामा कल आएंगे",
        "anchor_en": "My uncle will come tomorrow",
        "near_en":   "My uncle will arrive tomorrow",
        "far_en":    "My uncle will come tomorrow",
        "notes": "chacha = paternal uncle (father's younger brother); mama = maternal uncle (mother's brother). English collapses both to 'uncle'.",
    },
    {
        "id": "hi_kin_002",
        "anchor": "दादी ने मुझे कहानी सुनाई",
        "near":   "दादी ने मुझे कहानी बताई",
        "far":    "नानी ने मुझे कहानी सुनाई",
        "anchor_en": "Grandmother told me a story",
        "near_en":   "Grandmother told me a story",
        "far_en":    "Grandmother told me a story",
        "notes": "dadi = paternal grandmother; nani = maternal grandmother. sunaai/bataai are near-synonyms ('narrated'/'told').",
    },
    {
        "id": "hi_kin_003",
        "anchor": "बुआ का घर बहुत बड़ा है",
        "near":   "बुआ का मकान बहुत बड़ा है",
        "far":    "मौसी का घर बहुत बड़ा है",
        "anchor_en": "My aunt's house is very big",
        "near_en":   "My aunt's house is very big",
        "far_en":    "My aunt's house is very big",
        "notes": "bua = father's sister; mausi = mother's sister. ghar/makaan both = 'house'.",
    },
    {
        "id": "hi_kin_004",
        "anchor": "मेरे दादा बहुत मेहनती थे",
        "near":   "मेरे दादा अत्यंत मेहनती थे",
        "far":    "मेरे नाना बहुत मेहनती थे",
        "anchor_en": "My grandfather was very hardworking",
        "near_en":   "My grandfather was extremely hardworking",
        "far_en":    "My grandfather was very hardworking",
        "notes": "dada = paternal grandfather; nana = maternal grandfather.",
    },
    {
        "id": "hi_kin_005",
        "anchor": "चाची ने खाना बनाया",
        "near":   "चाची ने भोजन तैयार किया",
        "far":    "मामी ने खाना बनाया",
        "anchor_en": "My aunt cooked food",
        "near_en":   "My aunt prepared the meal",
        "far_en":    "My aunt cooked food",
        "notes": "chachi = wife of father's younger brother; mami = wife of mother's brother.",
    },
    {
        "id": "hi_kin_006",
        "anchor": "फूफा जी का काम बहुत अच्छा है",
        "near":   "फूफा जी का व्यवसाय बहुत अच्छा है",
        "far":    "मौसा जी का काम बहुत अच्छा है",
        "anchor_en": "My uncle's work is very good",
        "near_en":   "My uncle's business is very good",
        "far_en":    "My uncle's work is very good",
        "notes": "phupha = husband of father's sister; mausa = husband of mother's sister.",
    },
    {
        "id": "hi_kin_007",
        "anchor": "चाचा जी हमारे साथ रहते हैं",
        "near":   "चाचा जी हमारे यहाँ रहते हैं",
        "far":    "मामा जी हमारे साथ रहते हैं",
        "anchor_en": "My uncle lives with us",
        "near_en":   "My uncle lives at our place",
        "far_en":    "My uncle lives with us",
        "notes": "chacha = paternal uncle; mama = maternal uncle.",
    },
    {
        "id": "hi_kin_008",
        "anchor": "नानी मुझसे बहुत प्यार करती थीं",
        "near":   "नानी मुझसे अत्यधिक प्यार करती थीं",
        "far":    "दादी मुझसे बहुत प्यार करती थीं",
        "anchor_en": "Grandmother loved me very much",
        "near_en":   "Grandmother loved me a great deal",
        "far_en":    "Grandmother loved me very much",
        "notes": "nani = maternal grandmother; dadi = paternal grandmother.",
    },
    {
        "id": "hi_kin_009",
        "anchor": "चाचा जी की आवाज़ बहुत मीठी है",
        "near":   "चाचा जी की आवाज़ बहुत मधुर है",
        "far":    "मामा जी की आवाज़ बहुत मीठी है",
        "anchor_en": "My uncle's voice is very sweet",
        "near_en":   "My uncle's voice is very melodious",
        "far_en":    "My uncle's voice is very sweet",
        "notes": "chacha = paternal uncle; mama = maternal uncle. meethi/madhur both ≈ 'sweet/melodious'.",
    },
    {
        "id": "hi_kin_010",
        "anchor": "मेरी बुआ अमेरिका में रहती हैं",
        "near":   "मेरी बुआ अमेरिका में निवास करती हैं",
        "far":    "मेरी मौसी अमेरिका में रहती हैं",
        "anchor_en": "My aunt lives in America",
        "near_en":   "My aunt resides in America",
        "far_en":    "My aunt lives in America",
        "notes": "bua = father's sister; mausi = mother's sister.",
    },
    {
        "id": "hi_kin_011",
        "anchor": "ताऊ जी कल हमारे घर आए",
        "near":   "ताऊ जी कल हमारे घर पधारे",
        "far":    "मामा जी कल हमारे घर आए",
        "anchor_en": "My uncle came to our house yesterday",
        "near_en":   "My uncle came to our house yesterday",
        "far_en":    "My uncle came to our house yesterday",
        "notes": "tau = elder paternal uncle (father's older brother); mama = maternal uncle. aae/padhaare both = 'came', padhaare is more honorific.",
    },
    {
        "id": "hi_kin_012",
        "anchor": "दादा जी कहानियाँ सुनाते हैं",
        "near":   "दादा जी कहानियाँ बताते हैं",
        "far":    "नाना जी कहानियाँ सुनाते हैं",
        "anchor_en": "Grandfather tells stories",
        "near_en":   "Grandfather tells stories",
        "far_en":    "Grandfather tells stories",
        "notes": "dada = paternal grandfather; nana = maternal grandfather.",
    },
    {
        "id": "hi_kin_013",
        "anchor": "मेरी चाची बहुत समझदार हैं",
        "near":   "मेरी चाची बहुत बुद्धिमान हैं",
        "far":    "मेरी मामी बहुत समझदार हैं",
        "anchor_en": "My aunt is very wise",
        "near_en":   "My aunt is very intelligent",
        "far_en":    "My aunt is very wise",
        "notes": "chachi = paternal uncle's wife; mami = maternal uncle's wife.",
    },
]

# ============================================================================
# HINDI — kinship: relative age
# ============================================================================
# NOTE: English does distinguish "elder/younger" via modifiers, so this category
# is *partial flattening* — Hindi has it lexicalized, English requires extra words.
# That's the contrastive baseline for the strong-flattening categories.
hi_age = [
    {
        "id": "hi_age_001",
        "anchor": "मेरा बड़ा भाई स्कूल जाता है",
        "near":   "मेरा बड़ा भाई विद्यालय जाता है",
        "far":    "मेरा छोटा भाई स्कूल जाता है",
        "anchor_en": "My elder brother goes to school",
        "near_en":   "My elder brother goes to school",
        "far_en":    "My younger brother goes to school",
        "notes": "bada bhai = elder brother; chhota bhai = younger brother. English preserves via 'elder/younger'.",
    },
    {
        "id": "hi_age_002",
        "anchor": "मेरी बड़ी बहन डॉक्टर है",
        "near":   "मेरी बड़ी बहन चिकित्सक है",
        "far":    "मेरी छोटी बहन डॉक्टर है",
        "anchor_en": "My elder sister is a doctor",
        "near_en":   "My elder sister is a physician",
        "far_en":    "My younger sister is a doctor",
        "notes": "badi bahan = elder sister; chhoti bahan = younger sister.",
    },
    {
        "id": "hi_age_003",
        "anchor": "छोटे भाई ने खाना खाया",
        "near":   "छोटे भाई ने भोजन किया",
        "far":    "बड़े भाई ने खाना खाया",
        "anchor_en": "Younger brother ate food",
        "near_en":   "Younger brother had a meal",
        "far_en":    "Elder brother ate food",
        "notes": "chhota/bada bhai contrast.",
    },
    {
        "id": "hi_age_004",
        "anchor": "बड़ी बहन ने मुझे राय दी",
        "near":   "बड़ी बहन ने मुझे सलाह दी",
        "far":    "छोटी बहन ने मुझे राय दी",
        "anchor_en": "Elder sister gave me advice",
        "near_en":   "Elder sister gave me counsel",
        "far_en":    "Younger sister gave me advice",
        "notes": "raai/salaah both = 'advice'.",
    },
    {
        "id": "hi_age_005",
        "anchor": "छोटी बहन को संगीत पसंद है",
        "near":   "छोटी बहन को संगीत प्रिय है",
        "far":    "बड़ी बहन को संगीत पसंद है",
        "anchor_en": "Younger sister likes music",
        "near_en":   "Younger sister loves music",
        "far_en":    "Elder sister likes music",
        "notes": "pasand/priya both convey 'liking/fondness'.",
    },
    {
        "id": "hi_age_006",
        "anchor": "बड़े भाई की शादी हो गई",
        "near":   "बड़े भाई का विवाह हो गया",
        "far":    "छोटे भाई की शादी हो गई",
        "anchor_en": "Elder brother got married",
        "near_en":   "Elder brother got married",
        "far_en":    "Younger brother got married",
        "notes": "shaadi/vivaah both = 'marriage'.",
    },
    {
        "id": "hi_age_007",
        "anchor": "मेरी दीदी कल आ रही है",
        "near":   "मेरी दीदी कल आने वाली है",
        "far":    "मेरी छोटी बहन कल आ रही है",
        "anchor_en": "My elder sister is coming tomorrow",
        "near_en":   "My elder sister is going to come tomorrow",
        "far_en":    "My younger sister is coming tomorrow",
        "notes": "didi = elder sister (kinship-implicit age); chhoti bahan = younger sister.",
    },
    {
        "id": "hi_age_008",
        "anchor": "भैया ने मुझे साइकिल दी",
        "near":   "भैया ने मुझे साइकिल दिलाई",
        "far":    "छोटे भाई ने मुझे साइकिल दी",
        "anchor_en": "Elder brother gave me a bicycle",
        "near_en":   "Elder brother got me a bicycle",
        "far_en":    "Younger brother gave me a bicycle",
        "notes": "bhaiya = elder brother; chhota bhai = younger brother.",
    },
    {
        "id": "hi_age_009",
        "anchor": "बड़े भाई का घर पास में है",
        "near":   "बड़े भाई का मकान पास में है",
        "far":    "छोटे भाई का घर पास में है",
        "anchor_en": "Elder brother's house is nearby",
        "near_en":   "Elder brother's house is nearby",
        "far_en":    "Younger brother's house is nearby",
        "notes": "ghar/makaan both = 'house'.",
    },
    {
        "id": "hi_age_010",
        "anchor": "मेरी बड़ी बहन ने पहले शादी की",
        "near":   "मेरी बड़ी बहन ने पहले विवाह किया",
        "far":    "मेरी छोटी बहन ने पहले शादी की",
        "anchor_en": "My elder sister got married first",
        "near_en":   "My elder sister got married first",
        "far_en":    "My younger sister got married first",
        "notes": "shaadi/vivaah synonyms.",
    },
    {
        "id": "hi_age_011",
        "anchor": "छोटे भाई को क्रिकेट पसंद है",
        "near":   "छोटे भाई को क्रिकेट प्रिय है",
        "far":    "बड़े भाई को क्रिकेट पसंद है",
        "anchor_en": "Younger brother likes cricket",
        "near_en":   "Younger brother is fond of cricket",
        "far_en":    "Elder brother likes cricket",
        "notes": "pasand/priya synonyms.",
    },
    {
        "id": "hi_age_012",
        "anchor": "बड़ी बहन रोज़ योग करती है",
        "near":   "बड़ी बहन प्रतिदिन योग करती है",
        "far":    "छोटी बहन रोज़ योग करती है",
        "anchor_en": "Elder sister does yoga daily",
        "near_en":   "Elder sister does yoga daily",
        "far_en":    "Younger sister does yoga daily",
        "notes": "roz/pratidin both = 'daily'.",
    },
]

# ============================================================================
# HINDI — verb gender agreement
# ============================================================================
# Strategy: first-person past intransitives (gayi/gaya, aayi/aaya) and
# adjective+copula pairs (thaki/thaka, khush thi/tha). The subject "main"/"मैं"
# is gender-neutral in form, so the only morphological cue to speaker gender
# is the verb/adjective ending. English fully neutralizes ("I went").
hi_vga = [
    {
        "id": "hi_vga_001",
        "anchor": "मैं कल बाजार गई",
        "near":   "मैं कल दुकान गई",
        "far":    "मैं कल बाजार गया",
        "anchor_en": "I went to the market yesterday",
        "near_en":   "I went to the shop yesterday",
        "far_en":    "I went to the market yesterday",
        "notes": "gayi (fem.) vs gaya (masc.); 'main' (I) is morphologically neutral. English neutralizes.",
    },
    {
        "id": "hi_vga_002",
        "anchor": "मैं बहुत थकी हूँ",
        "near":   "मैं काफी थकी हूँ",
        "far":    "मैं बहुत थका हूँ",
        "anchor_en": "I am very tired",
        "near_en":   "I am quite tired",
        "far_en":    "I am very tired",
        "notes": "thaki (fem.) vs thaka (masc.).",
    },
    {
        "id": "hi_vga_003",
        "anchor": "मैं स्कूल पहुँच गई",
        "near":   "मैं विद्यालय पहुँच गई",
        "far":    "मैं स्कूल पहुँच गया",
        "anchor_en": "I reached school",
        "near_en":   "I reached school",
        "far_en":    "I reached school",
        "notes": "school/vidyalay both = 'school'; pahunch gayi (fem.) vs gaya (masc.).",
    },
    {
        "id": "hi_vga_004",
        "anchor": "मैं कल बहुत खुश थी",
        "near":   "मैं कल अत्यंत खुश थी",
        "far":    "मैं कल बहुत खुश था",
        "anchor_en": "I was very happy yesterday",
        "near_en":   "I was extremely happy yesterday",
        "far_en":    "I was very happy yesterday",
        "notes": "thi (fem. copula) vs tha (masc. copula).",
    },
    {
        "id": "hi_vga_005",
        "anchor": "मैं देर से उठी",
        "near":   "मैं देर से जागी",
        "far":    "मैं देर से उठा",
        "anchor_en": "I got up late",
        "near_en":   "I got up late",
        "far_en":    "I got up late",
        "notes": "uthi/jaagi both fem. ('woke/got up'); utha = masc.",
    },
    {
        "id": "hi_vga_006",
        "anchor": "मैं अकेली रह गई",
        "near":   "मैं अकेली बच गई",
        "far":    "मैं अकेला रह गया",
        "anchor_en": "I was left alone",
        "near_en":   "I was the only one left",
        "far_en":    "I was left alone",
        "notes": "akeli rah gayi (fem.) vs akela rah gaya (masc.).",
    },
    {
        "id": "hi_vga_007",
        "anchor": "मैं डर गया",
        "near":   "मैं घबरा गया",
        "far":    "मैं डर गई",
        "anchor_en": "I got scared",
        "near_en":   "I got nervous",
        "far_en":    "I got scared",
        "notes": "dar gaya (masc.) vs dar gayi (fem.); flipped polarity from previous items.",
    },
    {
        "id": "hi_vga_008",
        "anchor": "मैं कॉलेज से लौटा",
        "near":   "मैं कॉलेज से वापस आया",
        "far":    "मैं कॉलेज से लौटी",
        "anchor_en": "I returned from college",
        "near_en":   "I came back from college",
        "far_en":    "I returned from college",
        "notes": "lauta/aaya both masc. forms; lauti = fem.",
    },
    {
        "id": "hi_vga_009",
        "anchor": "मैं बीमार हो गई",
        "near":   "मैं अस्वस्थ हो गई",
        "far":    "मैं बीमार हो गया",
        "anchor_en": "I got sick",
        "near_en":   "I became unwell",
        "far_en":    "I got sick",
        "notes": "ho gayi (fem.) vs ho gaya (masc.).",
    },
    {
        "id": "hi_vga_010",
        "anchor": "मैं गुस्से में चला गया",
        "near":   "मैं गुस्से में निकल गया",
        "far":    "मैं गुस्से में चली गई",
        "anchor_en": "I left in anger",
        "near_en":   "I walked off in anger",
        "far_en":    "I left in anger",
        "notes": "chala gaya (masc.) vs chali gayi (fem.).",
    },
    {
        "id": "hi_vga_011",
        "anchor": "मैं देर तक सोई",
        "near":   "मैं देर तक सोती रही",
        "far":    "मैं देर तक सोया",
        "anchor_en": "I slept till late",
        "near_en":   "I kept sleeping till late",
        "far_en":    "I slept till late",
        "notes": "soyi/soti rahi (fem.) vs soya (masc.).",
    },
    {
        "id": "hi_vga_012",
        "anchor": "मैं स्टेशन पहुँचा",
        "near":   "मैं स्टेशन पर पहुँचा",
        "far":    "मैं स्टेशन पहुँची",
        "anchor_en": "I reached the station",
        "near_en":   "I reached the station",
        "far_en":    "I reached the station",
        "notes": "pahunchaa (masc.) vs pahunchi (fem.). Near is a postpositional variant.",
    },
    {
        "id": "hi_vga_013",
        "anchor": "मैं बहुत डरी हुई थी",
        "near":   "मैं अत्यधिक डरी हुई थी",
        "far":    "मैं बहुत डरा हुआ था",
        "anchor_en": "I was very scared",
        "near_en":   "I was extremely scared",
        "far_en":    "I was very scared",
        "notes": "dari hui thi (fem.) vs dara hua tha (masc.).",
    },
]

# ============================================================================
# HINDI — formality (T-V distinction): tu / tum / aap
# ============================================================================
hi_for = [
    {
        "id": "hi_for_001",
        "anchor": "तुम कैसे हो?",
        "near":   "तुम कैसे हो भाई?",
        "far":    "आप कैसे हैं?",
        "anchor_en": "How are you?",
        "near_en":   "How are you, brother?",
        "far_en":    "How are you?",
        "notes": "tum = informal you (sg); aap = formal you. English collapses to 'you'.",
    },
    {
        "id": "hi_for_002",
        "anchor": "तुम क्या कर रहे हो?",
        "near":   "तुम अभी क्या कर रहे हो?",
        "far":    "आप क्या कर रहे हैं?",
        "anchor_en": "What are you doing?",
        "near_en":   "What are you doing right now?",
        "far_en":    "What are you doing?",
        "notes": "tum/aap formality contrast.",
    },
    {
        "id": "hi_for_003",
        "anchor": "तू कहाँ जा रहा है?",
        "near":   "तू अभी कहाँ जा रहा है?",
        "far":    "आप कहाँ जा रहे हैं?",
        "anchor_en": "Where are you going?",
        "near_en":   "Where are you going right now?",
        "far_en":    "Where are you going?",
        "notes": "tu = very informal/intimate (or rude); aap = formal.",
    },
    {
        "id": "hi_for_004",
        "anchor": "तुम्हारा नाम क्या है?",
        "near":   "तुम अपना नाम बताओ",
        "far":    "आपका नाम क्या है?",
        "anchor_en": "What is your name?",
        "near_en":   "Tell me your name",
        "far_en":    "What is your name?",
        "notes": "tumhara (informal possessive) vs aapka (formal possessive).",
    },
    {
        "id": "hi_for_005",
        "anchor": "आप क्या लेंगे?",
        "near":   "आप क्या ऑर्डर करेंगे?",
        "far":    "तुम क्या लोगे?",
        "anchor_en": "What will you have?",
        "near_en":   "What will you order?",
        "far_en":    "What will you have?",
        "notes": "Anchor formal, far informal — flipped polarity.",
    },
    {
        "id": "hi_for_006",
        "anchor": "क्या आप मेरी मदद करेंगे?",
        "near":   "क्या आप मेरी सहायता करेंगे?",
        "far":    "क्या तुम मेरी मदद करोगे?",
        "anchor_en": "Will you help me?",
        "near_en":   "Will you assist me?",
        "far_en":    "Will you help me?",
        "notes": "madad/sahaayata both = 'help'.",
    },
    {
        "id": "hi_for_007",
        "anchor": "तुम कब आओगे?",
        "near":   "तुम कब पहुँचोगे?",
        "far":    "आप कब आएंगे?",
        "anchor_en": "When will you come?",
        "near_en":   "When will you arrive?",
        "far_en":    "When will you come?",
        "notes": "tum/aap formality contrast.",
    },
    {
        "id": "hi_for_008",
        "anchor": "आपका घर कहाँ है?",
        "near":   "आपका मकान कहाँ है?",
        "far":    "तुम्हारा घर कहाँ है?",
        "anchor_en": "Where is your house?",
        "near_en":   "Where is your house?",
        "far_en":    "Where is your house?",
        "notes": "aapka (formal) vs tumhara (informal); ghar/makaan both = 'house'.",
    },
    {
        "id": "hi_for_009",
        "anchor": "तू मेरा सबसे अच्छा दोस्त है",
        "near":   "तू मेरा सबसे प्यारा दोस्त है",
        "far":    "आप मेरे सबसे अच्छे दोस्त हैं",
        "anchor_en": "You are my best friend",
        "near_en":   "You are my dearest friend",
        "far_en":    "You are my best friend",
        "notes": "tu (intimate) vs aap (formal). Note: 'aap' for a best friend is pragmatically marked but grammatical.",
    },
    {
        "id": "hi_for_010",
        "anchor": "तुम बहुत अच्छा गाते हो",
        "near":   "तुम बहुत बढ़िया गाते हो",
        "far":    "आप बहुत अच्छा गाते हैं",
        "anchor_en": "You sing very well",
        "near_en":   "You sing very well",
        "far_en":    "You sing very well",
        "notes": "achchha/badhiya both = 'good/well'.",
    },
    {
        "id": "hi_for_011",
        "anchor": "आप कहाँ रहते हैं?",
        "near":   "आप कहाँ निवास करते हैं?",
        "far":    "तुम कहाँ रहते हो?",
        "anchor_en": "Where do you live?",
        "near_en":   "Where do you reside?",
        "far_en":    "Where do you live?",
        "notes": "rahna/nivaas karna both = 'live/reside'.",
    },
    {
        "id": "hi_for_012",
        "anchor": "तुम मुझे क्यों परेशान कर रहे हो?",
        "near":   "तुम मुझे क्यों तंग कर रहे हो?",
        "far":    "आप मुझे क्यों परेशान कर रहे हैं?",
        "anchor_en": "Why are you bothering me?",
        "near_en":   "Why are you troubling me?",
        "far_en":    "Why are you bothering me?",
        "notes": "pareshaan/tang both = 'bother/trouble'.",
    },
]

# ============================================================================
# SPANISH — ser vs. estar
# ============================================================================
# Mostly flattening cases (English: "is X" for both ser and estar).
# A few non-flattening items included intentionally as within-category contrast
# (es aburrido = "is boring" vs está aburrido = "is bored", etc.) — these are
# noted so Adyant can stratify in the per-item analysis.
es_ser = [
    {
        "id": "es_ser_001",
        "anchor": "Pedro es alto",
        "near":   "Pedro es muy alto",
        "far":    "Pedro está alto",
        "anchor_en": "Pedro is tall",
        "near_en":   "Pedro is very tall",
        "far_en":    "Pedro is tall",
        "notes": "es alto = tall (inherent); está alto = has gotten tall / looks tall now. English: 'is tall' for both — strong flattening.",
    },
    {
        "id": "es_ser_002",
        "anchor": "Mi madre es joven",
        "near":   "Mi madre todavía es joven",
        "far":    "Mi madre está joven",
        "anchor_en": "My mother is young",
        "near_en":   "My mother is still young",
        "far_en":    "My mother is young",
        "notes": "es joven = young (age fact); está joven = looks young / youthful now. English flattens.",
    },
    {
        "id": "es_ser_003",
        "anchor": "Carlos es guapo",
        "near":   "Carlos es bastante guapo",
        "far":    "Carlos está guapo",
        "anchor_en": "Carlos is handsome",
        "near_en":   "Carlos is quite handsome",
        "far_en":    "Carlos is handsome",
        "notes": "es guapo = handsome (trait); está guapo = looks handsome (today/in this outfit). English flattens.",
    },
    {
        "id": "es_ser_004",
        "anchor": "Ella es delgada",
        "near":   "Ella es bastante delgada",
        "far":    "Ella está delgada",
        "anchor_en": "She is thin",
        "near_en":   "She is quite thin",
        "far_en":    "She is thin",
        "notes": "es delgada = thin (build); está delgada = has gotten thin. English flattens.",
    },
    {
        "id": "es_ser_005",
        "anchor": "Esta sopa es buena",
        "near":   "Esta sopa es muy buena",
        "far":    "Esta sopa está buena",
        "anchor_en": "This soup is good",
        "near_en":   "This soup is very good",
        "far_en":    "This soup is good",
        "notes": "es buena = good quality (e.g., for you); está buena = tastes good right now. English 'is good' for both — partial flattening.",
    },
    {
        "id": "es_ser_006",
        "anchor": "Pedro es nervioso",
        "near":   "Pedro es una persona nerviosa",
        "far":    "Pedro está nervioso",
        "anchor_en": "Pedro is nervous",
        "near_en":   "Pedro is a nervous person",
        "far_en":    "Pedro is nervous",
        "notes": "es nervioso = nervous by nature; está nervioso = nervous right now. English flattens.",
    },
    {
        "id": "es_ser_007",
        "anchor": "Mi hermano es callado",
        "near":   "Mi hermano es bastante callado",
        "far":    "Mi hermano está callado",
        "anchor_en": "My brother is quiet",
        "near_en":   "My brother is quite quiet",
        "far_en":    "My brother is quiet",
        "notes": "es callado = quiet personality; está callado = silent right now. English flattens.",
    },
    {
        "id": "es_ser_008",
        "anchor": "El profesor es estricto",
        "near":   "El profesor es muy estricto",
        "far":    "El profesor está estricto",
        "anchor_en": "The teacher is strict",
        "near_en":   "The teacher is very strict",
        "far_en":    "The teacher is strict",
        "notes": "es estricto = strict by nature; está estricto = being strict today. English flattens.",
    },
    {
        "id": "es_ser_009",
        "anchor": "Esta habitación es bonita",
        "near":   "Esta habitación es muy bonita",
        "far":    "Esta habitación está bonita",
        "anchor_en": "This room is pretty",
        "near_en":   "This room is very pretty",
        "far_en":    "This room is pretty",
        "notes": "es bonita = inherently pretty; está bonita = looks pretty (today/freshly cleaned). English flattens.",
    },
    {
        "id": "es_ser_010",
        "anchor": "Tu amiga es simpática",
        "near":   "Tu amiga es bastante simpática",
        "far":    "Tu amiga está simpática",
        "anchor_en": "Your friend is nice",
        "near_en":   "Your friend is quite nice",
        "far_en":    "Your friend is nice",
        "notes": "es simpática = nice by nature; está simpática = being nice today. English flattens.",
    },
    {
        "id": "es_ser_011",
        "anchor": "Marta es bonita",
        "near":   "Marta es realmente bonita",
        "far":    "Marta está bonita",
        "anchor_en": "Marta is pretty",
        "near_en":   "Marta is really pretty",
        "far_en":    "Marta is pretty",
        "notes": "es bonita = pretty (inherent); está bonita = looks pretty today. English flattens.",
    },
    {
        "id": "es_ser_012",
        "anchor": "Mi profesor es aburrido",
        "near":   "Mi profesor es una persona aburrida",
        "far":    "Mi profesor está aburrido",
        "anchor_en": "My teacher is boring",
        "near_en":   "My teacher is a boring person",
        "far_en":    "My teacher is bored",
        "notes": "es aburrido = boring (trait); está aburrido = bored (state). English DISTINGUISHES — non-flattening case. Useful as in-category contrast.",
    },
    {
        "id": "es_ser_013",
        "anchor": "Roberto es listo",
        "near":   "Roberto es muy listo",
        "far":    "Roberto está listo",
        "anchor_en": "Roberto is smart",
        "near_en":   "Roberto is very smart",
        "far_en":    "Roberto is ready",
        "notes": "es listo = smart; está listo = ready. English distinguishes — non-flattening.",
    },
    {
        "id": "es_ser_014",
        "anchor": "Antonio es malo",
        "near":   "Antonio es una persona mala",
        "far":    "Antonio está malo",
        "anchor_en": "Antonio is bad",
        "near_en":   "Antonio is a bad person",
        "far_en":    "Antonio is sick",
        "notes": "es malo = bad person; está malo = is sick (or food has gone off). English distinguishes — non-flattening.",
    },
    {
        "id": "es_ser_015",
        "anchor": "Mi hijo es tranquilo",
        "near":   "Mi hijo es muy tranquilo",
        "far":    "Mi hijo está tranquilo",
        "anchor_en": "My son is calm",
        "near_en":   "My son is very calm",
        "far_en":    "My son is calm",
        "notes": "es tranquilo = calm temperament; está tranquilo = calm right now. English flattens.",
    },
    {
        "id": "es_ser_016",
        "anchor": "Mi tía es alegre",
        "near":   "Mi tía es una persona alegre",
        "far":    "Mi tía está alegre",
        "anchor_en": "My aunt is cheerful",
        "near_en":   "My aunt is a cheerful person",
        "far_en":    "My aunt is cheerful",
        "notes": "es alegre = cheerful disposition; está alegre = cheerful (or tipsy) right now. English flattens.",
    },
    {
        "id": "es_ser_017",
        "anchor": "El paisaje es hermoso",
        "near":   "El paisaje es realmente hermoso",
        "far":    "El paisaje está hermoso",
        "anchor_en": "The landscape is beautiful",
        "near_en":   "The landscape is really beautiful",
        "far_en":    "The landscape is beautiful",
        "notes": "es hermoso = inherently beautiful; está hermoso = looks beautiful (in this light/season). English flattens.",
    },
]

# ============================================================================
# SPANISH — formality (tú/usted, vosotros/ustedes)
# ============================================================================
es_for = [
    {
        "id": "es_for_001",
        "anchor": "¿Cómo estás?",
        "near":   "¿Qué tal estás?",
        "far":    "¿Cómo está?",
        "anchor_en": "How are you?",
        "near_en":   "How are you doing?",
        "far_en":    "How are you?",
        "notes": "tú vs usted — English collapses to 'you'.",
    },
    {
        "id": "es_for_002",
        "anchor": "¿De dónde eres?",
        "near":   "¿De qué lugar eres?",
        "far":    "¿De dónde es?",
        "anchor_en": "Where are you from?",
        "near_en":   "Where are you from?",
        "far_en":    "Where are you from?",
        "notes": "eres (tú) vs es (usted).",
    },
    {
        "id": "es_for_003",
        "anchor": "¿Quieres un café?",
        "near":   "¿Te apetece un café?",
        "far":    "¿Quiere un café?",
        "anchor_en": "Do you want a coffee?",
        "near_en":   "Would you like a coffee?",
        "far_en":    "Do you want a coffee?",
        "notes": "quieres (tú) vs quiere (usted).",
    },
    {
        "id": "es_for_004",
        "anchor": "¿Tienes hambre?",
        "near":   "¿Estás con hambre?",
        "far":    "¿Tiene hambre?",
        "anchor_en": "Are you hungry?",
        "near_en":   "Are you hungry?",
        "far_en":    "Are you hungry?",
        "notes": "tienes/estás con hambre informal; tiene formal.",
    },
    {
        "id": "es_for_005",
        "anchor": "¿Puedes ayudarme?",
        "near":   "¿Me puedes ayudar?",
        "far":    "¿Puede ayudarme?",
        "anchor_en": "Can you help me?",
        "near_en":   "Can you help me?",
        "far_en":    "Can you help me?",
        "notes": "Near is a clitic-position variant.",
    },
    {
        "id": "es_for_006",
        "anchor": "¿A qué hora vienes?",
        "near":   "¿A qué hora llegas?",
        "far":    "¿A qué hora viene?",
        "anchor_en": "What time are you coming?",
        "near_en":   "What time are you arriving?",
        "far_en":    "What time are you coming?",
        "notes": "vienes/llegas informal; viene formal.",
    },
    {
        "id": "es_for_007",
        "anchor": "¿Vives cerca de aquí?",
        "near":   "¿Vives en este barrio?",
        "far":    "¿Vive cerca de aquí?",
        "anchor_en": "Do you live near here?",
        "near_en":   "Do you live in this neighborhood?",
        "far_en":    "Do you live near here?",
        "notes": "vives (tú) vs vive (usted).",
    },
    {
        "id": "es_for_008",
        "anchor": "¿Hablas inglés?",
        "near":   "¿Sabes hablar inglés?",
        "far":    "¿Habla inglés?",
        "anchor_en": "Do you speak English?",
        "near_en":   "Do you know how to speak English?",
        "far_en":    "Do you speak English?",
        "notes": "hablas (tú) vs habla (usted).",
    },
    {
        "id": "es_for_009",
        "anchor": "Tú eres muy amable",
        "near":   "Tú eres una persona muy amable",
        "far":    "Usted es muy amable",
        "anchor_en": "You are very kind",
        "near_en":   "You are a very kind person",
        "far_en":    "You are very kind",
        "notes": "tú/usted contrast.",
    },
    {
        "id": "es_for_010",
        "anchor": "Vosotros sois muy graciosos",
        "near":   "Vosotros sois bastante graciosos",
        "far":    "Ustedes son muy graciosos",
        "anchor_en": "You are very funny",
        "near_en":   "You are quite funny",
        "far_en":    "You are very funny",
        "notes": "vosotros (Spain informal pl.) vs ustedes (formal/LatAm pl.). English collapses.",
    },
    {
        "id": "es_for_011",
        "anchor": "¿Vosotros venís a la fiesta?",
        "near":   "¿Vosotros vais a venir a la fiesta?",
        "far":    "¿Ustedes vienen a la fiesta?",
        "anchor_en": "Are you coming to the party?",
        "near_en":   "Are you going to come to the party?",
        "far_en":    "Are you coming to the party?",
        "notes": "vosotros/ustedes plural formality.",
    },
    {
        "id": "es_for_012",
        "anchor": "¿Tienes tiempo ahora?",
        "near":   "¿Tienes un momento ahora?",
        "far":    "¿Tiene tiempo ahora?",
        "anchor_en": "Do you have time now?",
        "near_en":   "Do you have a moment now?",
        "far_en":    "Do you have time now?",
        "notes": "tienes/tiene formality.",
    },
    {
        "id": "es_for_013",
        "anchor": "Tu hijo es muy listo",
        "near":   "Tu hijo es bastante listo",
        "far":    "Su hijo es muy listo",
        "anchor_en": "Your son is very smart",
        "near_en":   "Your son is quite smart",
        "far_en":    "Your son is very smart",
        "notes": "tu (informal possessive) vs su (formal possessive — also ambiguous with 3rd-person 'his/her', acceptable in this context).",
    },
    {
        "id": "es_for_014",
        "anchor": "¿Cómo te llamas?",
        "near":   "¿Cuál es tu nombre?",
        "far":    "¿Cómo se llama?",
        "anchor_en": "What is your name?",
        "near_en":   "What is your name?",
        "far_en":    "What is your name?",
        "notes": "te llamas (informal reflexive) vs se llama (formal).",
    },
    {
        "id": "es_for_015",
        "anchor": "Ven aquí, por favor",
        "near":   "Acércate aquí, por favor",
        "far":    "Venga aquí, por favor",
        "anchor_en": "Come here, please",
        "near_en":   "Come closer, please",
        "far_en":    "Come here, please",
        "notes": "ven (informal imperative) vs venga (formal imperative).",
    },
    {
        "id": "es_for_016",
        "anchor": "¿Quieres ir al cine?",
        "near":   "¿Te apetece ir al cine?",
        "far":    "¿Quiere ir al cine?",
        "anchor_en": "Do you want to go to the movies?",
        "near_en":   "Would you like to go to the movies?",
        "far_en":    "Do you want to go to the movies?",
        "notes": "quieres/te apetece (informal) vs quiere (formal).",
    },
    {
        "id": "es_for_017",
        "anchor": "Dime tu opinión",
        "near":   "Cuéntame tu opinión",
        "far":    "Dígame su opinión",
        "anchor_en": "Tell me your opinion",
        "near_en":   "Tell me your opinion",
        "far_en":    "Tell me your opinion",
        "notes": "dime/cuéntame (informal imperative) vs dígame (formal imperative); tu/su possessive shift.",
    },
]

# ============================================================================
# SPANISH — gender agreement on adjectives
# ============================================================================
# Use gender-neutral English nouns ('friend', 'teacher', 'doctor', 'child',
# 'colleague', 'student', 'baby', 'client', 'journalist', 'artist', 'relative')
# so the gender info encoded in the Spanish noun+adjective doesn't leak into
# the English translation.
es_gen = [
    {
        "id": "es_gen_001",
        "anchor": "Mi amigo está cansado",
        "near":   "Mi amigo está agotado",
        "far":    "Mi amiga está cansada",
        "anchor_en": "My friend is tired",
        "near_en":   "My friend is exhausted",
        "far_en":    "My friend is tired",
        "notes": "amigo (m) / amiga (f); 'friend' is gender-neutral in English.",
    },
    {
        "id": "es_gen_002",
        "anchor": "Mi vecino es muy amable",
        "near":   "Mi vecino es bastante amable",
        "far":    "Mi vecina es muy amable",
        "anchor_en": "My neighbor is very kind",
        "near_en":   "My neighbor is quite kind",
        "far_en":    "My neighbor is very kind",
        "notes": "vecino/vecina; 'neighbor' is gender-neutral.",
    },
    {
        "id": "es_gen_003",
        "anchor": "El doctor está ocupado",
        "near":   "El doctor está trabajando",
        "far":    "La doctora está ocupada",
        "anchor_en": "The doctor is busy",
        "near_en":   "The doctor is working",
        "far_en":    "The doctor is busy",
        "notes": "doctor/doctora; 'doctor' is gender-neutral in English.",
    },
    {
        "id": "es_gen_004",
        "anchor": "Mi hijo está enfermo",
        "near":   "Mi hijo está mal",
        "far":    "Mi hija está enferma",
        "anchor_en": "My child is sick",
        "near_en":   "My child is unwell",
        "far_en":    "My child is sick",
        "notes": "hijo (son) / hija (daughter); translate as 'child' to preserve flattening.",
    },
    {
        "id": "es_gen_005",
        "anchor": "El profesor es muy estricto",
        "near":   "El profesor es bastante estricto",
        "far":    "La profesora es muy estricta",
        "anchor_en": "The teacher is very strict",
        "near_en":   "The teacher is quite strict",
        "far_en":    "The teacher is very strict",
        "notes": "profesor/profesora; 'teacher' is gender-neutral.",
    },
    {
        "id": "es_gen_006",
        "anchor": "Mi compañero es trabajador",
        "near":   "Mi compañero es muy trabajador",
        "far":    "Mi compañera es trabajadora",
        "anchor_en": "My colleague is hardworking",
        "near_en":   "My colleague is very hardworking",
        "far_en":    "My colleague is hardworking",
        "notes": "compañero/compañera; rendered as 'colleague' (gender-neutral).",
    },
    {
        "id": "es_gen_007",
        "anchor": "El abogado está enojado",
        "near":   "El abogado está furioso",
        "far":    "La abogada está enojada",
        "anchor_en": "The lawyer is angry",
        "near_en":   "The lawyer is furious",
        "far_en":    "The lawyer is angry",
        "notes": "abogado/abogada; 'lawyer' is gender-neutral.",
    },
    {
        "id": "es_gen_008",
        "anchor": "Mi primo está aburrido",
        "near":   "Mi primo no tiene nada que hacer",
        "far":    "Mi prima está aburrida",
        "anchor_en": "My cousin is bored",
        "near_en":   "My cousin has nothing to do",
        "far_en":    "My cousin is bored",
        "notes": "primo/prima; 'cousin' is gender-neutral.",
    },
    {
        "id": "es_gen_009",
        "anchor": "El niño está contento",
        "near":   "El niño está alegre",
        "far":    "La niña está contenta",
        "anchor_en": "The child is happy",
        "near_en":   "The child is cheerful",
        "far_en":    "The child is happy",
        "notes": "niño/niña; rendered as 'child'.",
    },
    {
        "id": "es_gen_010",
        "anchor": "El estudiante está nervioso",
        "near":   "El estudiante está preocupado",
        "far":    "La estudiante está nerviosa",
        "anchor_en": "The student is nervous",
        "near_en":   "The student is worried",
        "far_en":    "The student is nervous",
        "notes": "Spanish 'estudiante' is invariant in form; gender shows in the article (el/la) and adjective. English 'student' is gender-neutral.",
    },
    {
        "id": "es_gen_011",
        "anchor": "El bebé está dormido",
        "near":   "El bebé está descansando",
        "far":    "La bebé está dormida",
        "anchor_en": "The baby is asleep",
        "near_en":   "The baby is resting",
        "far_en":    "The baby is asleep",
        "notes": "Article el/la and adjective dormido/dormida carry the gender; 'bebé' invariant. English 'baby' gender-neutral.",
    },
    {
        "id": "es_gen_012",
        "anchor": "Mi cliente está satisfecho",
        "near":   "Mi cliente está conforme",
        "far":    "Mi clienta está satisfecha",
        "anchor_en": "My client is satisfied",
        "near_en":   "My client is in agreement",
        "far_en":    "My client is satisfied",
        "notes": "cliente/clienta; 'client' is gender-neutral.",
    },
    {
        "id": "es_gen_013",
        "anchor": "El periodista está cansado",
        "near":   "El periodista está fatigado",
        "far":    "La periodista está cansada",
        "anchor_en": "The journalist is tired",
        "near_en":   "The journalist is fatigued",
        "far_en":    "The journalist is tired",
        "notes": "'periodista' invariant in form; gender via article + adjective.",
    },
    {
        "id": "es_gen_014",
        "anchor": "Mi pariente está enfermo",
        "near":   "Mi pariente está mal",
        "far":    "Mi pariente está enferma",
        "anchor_en": "My relative is sick",
        "near_en":   "My relative is unwell",
        "far_en":    "My relative is sick",
        "notes": "'pariente' invariant in form; only the adjective ending (enfermo/enferma) carries gender. Very minimal pair.",
    },
    {
        "id": "es_gen_015",
        "anchor": "El artista es talentoso",
        "near":   "El artista es muy talentoso",
        "far":    "La artista es talentosa",
        "anchor_en": "The artist is talented",
        "near_en":   "The artist is very talented",
        "far_en":    "The artist is talented",
        "notes": "'artista' invariant in form; gender via article + adjective.",
    },
    {
        "id": "es_gen_016",
        "anchor": "Mi colega está enojado",
        "near":   "Mi colega está furioso",
        "far":    "Mi colega está enojada",
        "anchor_en": "My colleague is angry",
        "near_en":   "My colleague is furious",
        "far_en":    "My colleague is angry",
        "notes": "'colega' invariant in form; gender entirely on the adjective (enojado/enojada). Cleanest minimal pair in this category.",
    },
]

# ============================================================================
# Assemble
# ============================================================================
def add_meta(items, language, category):
    out = []
    for it in items:
        d = {
            "id": it["id"],
            "language": language,
            "category": category,
            "anchor": it["anchor"],
            "near": it["near"],
            "far": it["far"],
            "anchor_en": it["anchor_en"],
            "near_en": it["near_en"],
            "far_en": it["far_en"],
            "notes": it["notes"],
        }
        out.append(d)
    return out

triplets = []
triplets += add_meta(hi_kin, "hindi",   "kinship_paternal_maternal")
triplets += add_meta(hi_age, "hindi",   "kinship_relative_age")
triplets += add_meta(hi_vga, "hindi",   "verb_gender_agreement")
triplets += add_meta(hi_for, "hindi",   "formality_tv")
triplets += add_meta(es_ser, "spanish", "ser_vs_estar")
triplets += add_meta(es_for, "spanish", "formality")
triplets += add_meta(es_gen, "spanish", "gender_agreement_adjectives")

# ============================================================================
# Validation
# ============================================================================
required_fields = ["id","language","category","anchor","near","far","anchor_en","near_en","far_en","notes"]

ids_seen = set()
for t in triplets:
    for f in required_fields:
        assert f in t and t[f] != "", f"missing/empty {f} in {t.get('id','?')}"
    assert t["id"] not in ids_seen, f"duplicate id: {t['id']}"
    ids_seen.add(t["id"])

# Counts
from collections import Counter
counts_lang = Counter(t["language"] for t in triplets)
counts_cat  = Counter((t["language"], t["category"]) for t in triplets)

# Check no '(paternal)' or '(maternal)' or similar disambiguating glosses leaked into _en
for t in triplets:
    for f in ["anchor_en","near_en","far_en"]:
        s = t[f].lower()
        for bad in ["(paternal)","(maternal)","(elder)","(younger)","(formal)","(informal)","(masculine)","(feminine)","(male)","(female)"]:
            assert bad not in s, f"{t['id']} {f} leaks gloss: {t[f]}"

# Output
out_path = Path(__file__).parent / "triplets.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump({"triplets": triplets}, f, ensure_ascii=False, indent=2)

print(f"OK — wrote {len(triplets)} triplets to {out_path}")
print(f"  by language: {dict(counts_lang)}")
for (lang, cat), n in sorted(counts_cat.items()):
    print(f"    {lang:8s} {cat:30s} {n}")
